-- ============================================================
--  GameMate — Supabase şeması
--  Supabase Dashboard → SQL Editor'a yapıştırıp "Run" deyin.
--  (Veya: supabase db push)
-- ============================================================

-- ----------- Profiller (oyuncular + kayıtlı kullanıcılar) -----------
create table if not exists public.profiles (
  id          bigint generated by default as identity primary key,
  name        text not null,
  country     text default '🌐',
  age         int,
  online      boolean default true,
  admin       boolean default false,
  devices     text[] default '{}',          -- ['PC'] | ['PS5'] | ['PC','PS5']
  bio         text default '',
  tags        text[] default '{}',           -- etiket id'leri: friendly, competitive, ...
  socials     jsonb  default '{}'::jsonb,     -- { steam, discord, riot, steamUrl, ... }
  rating      numeric default 0,
  times       text[] default '{}',           -- aktif saatler: '19','20',...
  games       jsonb  default '[]'::jsonb,     -- [{ g, rank, role, roles, ps }]
  created_at  timestamptz default now()
);

-- ----------- İletişim mesajları -----------
create table if not exists public.contact_messages (
  id          bigint generated by default as identity primary key,
  name        text not null,
  email       text not null,
  subject     text default '',
  message     text not null,
  read        boolean default false,
  created_at  timestamptz default now()
);

-- ----------- Profil duvarı yorumları -----------
create table if not exists public.wall_comments (
  id          bigint generated by default as identity primary key,
  profile_id  bigint not null,               -- duvarın sahibi (oyuncu id)
  author      text not null,
  text        text not null,
  stars       int default 0,
  created_at  timestamptz default now()
);

-- ----------- Puanlar (oyuncu başına) -----------
create table if not exists public.ratings (
  profile_id  bigint primary key,
  stars       int not null,
  updated_at  timestamptz default now()
);

-- ----------- Banlar -----------
create table if not exists public.bans (
  profile_id  bigint primary key,
  banned_at   timestamptz default now()
);

-- ----------- Site ayarları (tek satır: id = 1) -----------
create table if not exists public.site_settings (
  id          int primary key default 1,
  site_cfg    jsonb,
  seo         jsonb,
  ads         jsonb,
  updated_at  timestamptz default now()
);

-- ============================================================
--  RLS (Row Level Security)
--  DİKKAT: Bu politikalar PROTOTIP içindir — anon (herkese açık)
--  okuma/yazmaya izin verir. Canlıya almadan önce Supabase Auth
--  ekleyip politikaları kısıtlayın (ör. yalnızca admin yazabilsin).
-- ============================================================
alter table public.profiles        enable row level security;
alter table public.contact_messages enable row level security;
alter table public.wall_comments   enable row level security;
alter table public.ratings         enable row level security;
alter table public.bans            enable row level security;
alter table public.site_settings   enable row level security;

do $$
declare t text;
begin
  foreach t in array array['profiles','contact_messages','wall_comments','ratings','bans','site_settings']
  loop
    execute format('drop policy if exists "anon_all_%1$s" on public.%1$I;', t);
    execute format('create policy "anon_all_%1$s" on public.%1$I for all to anon, authenticated using (true) with check (true);', t);
  end loop;
end$$;

-- ============================================================
--  Örnek veri (demo oyuncular)
-- ============================================================
insert into public.profiles (name, country, age, online, admin, devices, bio, tags, socials, rating, times, games) values
('NyxStorm', '🇹🇷', 23, true,  false, '{PC}',        'Rekabetçi ama eğlenceli. Sıralı maç partneri arıyorum.', '{competitive,tryhard,mic}', '{"steam":"nyxstorm","discord":"nyx#0021","riot":"NyxStorm#TR1"}', 4.8, '{19,20,21,22}', '[{"g":"valorant","rank":"Elmas","role":"Düellocu","roles":["Düellocu","Başlatıcı"],"ps":"Rekabetçi"}]'),
('AuroraMid',  '🇩🇪', 25, true,  false, '{PC}',        'Orta koridor main. Sakin ve iletişime açık.',             '{friendly,chill,mic}',      '{"riot":"Aurora#EUW","discord":"aurora#1133"}',                 4.6, '{20,21,22,23}', '[{"g":"lol","rank":"Platin","role":"Orta Koridor","roles":["Orta Koridor"],"ps":"Rekabetçi"}]'),
('FragKing',   '🇹🇷', 28, false, false, '{PC}',        'AWP''ci. Premier grind için takım arıyorum.',             '{competitive,tryhard}',     '{"steam":"fragking_","discord":"frag#0007"}',                   4.9, '{21,22,23}',    '[{"g":"cs2","rank":"Premier 15K","role":"AWP''ci","roles":["AWP''ci","Pusucu"],"ps":"Rekabetçi"}]'),
('PixelFox',   '🇫🇷', 21, true,  false, '{PC,PS5}',    'Apex sezon partneri. Hem PC hem PS5 oynarım.',            '{friendly,night,mic}',      '{"steam":"pixelfox","discord":"fox#2020","psn":"PixelFox_FR"}',  4.4, '{22,23,0,1}',   '[{"g":"apex","rank":"Platin","role":"Vurucu","roles":["Vurucu","Keşif"],"ps":"İkisi de"}]'),
('NovaBuild',  '🇹🇷', 19, true,  false, '{PS5}',       'Fortnite kurmaca canavarı. Eğlenmek için oynarım.',       '{friendly,chill}',          '{"psn":"NovaBuild","discord":"nova#5050"}',                      4.2, '{18,19,20}',    '[{"g":"fortnite","rank":"Elmas","role":"İnşaatçı","roles":["İnşaatçı","Vurucu"],"ps":"Günlük"}]'),
('TurboGoal',  '🇪🇸', 24, false, false, '{PS5}',       'Rocket League 2v2/3v3. Champ rütbesi.',                   '{competitive,mic}',         '{"psn":"TurboGoal","discord":"turbo#9090"}',                    4.5, '{20,21,22}',    '[{"g":"rocketleague","rank":"Şampiyon","role":"Orta Saha","roles":["Orta Saha","Forvet"],"ps":"Rekabetçi"}]'),
('HeistMango', '🇹🇷', 27, true,  false, '{PS5}',       'GTA Online soygun ekibi kuruyorum. Mikrofon şart.',       '{friendly,chill,mic}',      '{"psn":"HeistMango","discord":"mango#1212"}',                   4.1, '{21,22,23,0}',  '[{"g":"gta","rank":"Lv 100-300","role":"Soyguncu","roles":["Soyguncu","Sürücü"],"ps":"Günlük"}]'),
('SakuraOW',   '🇬🇧', 22, true,  false, '{PC,PS5}',    'Overwatch destek main. Sıralı için arkadaş arıyorum.',    '{competitive,friendly,mic}', '{"steam":"sakuraow","discord":"sakura#3030","psn":"SakuraOW"}', 4.7, '{19,20,21}',    '[{"g":"overwatch","rank":"Elmas","role":"Destek","roles":["Destek"],"ps":"Rekabetçi"}]'),
('ByteRunner', '🇹🇷', 26, true,  false, '{PC}',        'Marvel Rivals düellocu. 6v6 için takım arıyorum.',        '{competitive,mic}',          '{"steamUrl":"https://steamcommunity.com/id/byterunner","discord":"byte#0099"}', 4.5, '{20,21,22}',    '[{"g":"marvelrivals","rank":"Platin","role":"Düellocu","roles":["Düellocu"],"ps":"Rekabetçi"}]'),
('CrimsonFC',  '🇹🇷', 29, true,  false, '{PS5}',       'EA FC 26 Pro Club. Forvet oynuyorum, kulüp kuralım.',     '{friendly,competitive}',     '{"psn":"CrimsonFC","discord":"crimson#1212"}',                 4.3, '{21,22,23}',    '[{"g":"eafc","rank":"Div 3","role":"Forvet","roles":["Forvet","Kanat"],"ps":"Rekabetçi"}]'),
('GhostDiver', '🇳🇱', 24, true,  false, '{PC,PS5}',    'Helldivers 2 co-op. Zor görevlere birlikte gidelim.',     '{friendly,chill,mic}',       '{"steamUrl":"https://steamcommunity.com/id/ghostdiver","psn":"GhostDiver_NL","discord":"ghost#7777"}', 4.6, '{19,20,21,22}', '[{"g":"helldivers","rank":"Komando","role":"Destek","roles":["Destek","Ağır Silah"],"ps":"Günlük"}]'),
('RoleKingTR', '🇹🇷', 23, true,  false, '{PC}',        'FiveM Türk rol yapma. Ekip arıyorum, mikrofon şart.',     '{friendly,chill,mic}',       '{"discord":"roleking#3434"}',                                  4.2, '{20,21,22,23,0}', '[{"g":"fivem","rank":"Vatandaş","role":"Rol Yapma","roles":["Rol Yapma","Esnaf"],"ps":"Günlük"}]');

-- Varsayılan site ayarları satırı (uygulama ilk açılışta kendi de oluşturur)
insert into public.site_settings (id, site_cfg, seo, ads)
values (1,
  '{"logoSize":42,"landingScale":1.12,"footer":"© 2026 GameMate. Tüm hakları saklıdır."}'::jsonb,
  '{"title":"GameMate — Oyun Arkadaşı & Takım Bul (PC / PS5)","desc":"GameMate ile aynı oyunları oynayan, seninle uyumlu takım arkadaşları bul.","keywords":"oyun arkadaşı bul, duo bul, takım arkadaşı, valorant duo, lol takım, ps5 oyun arkadaşı, gamemate","ogImage":"https://gamemate.gg/og-cover.png","canonical":"https://gamemate.gg/","robots":"index, follow","twitter":"summary_large_image","siteName":"GameMate","locale":"tr_TR","twitterHandle":"@gamemate","themeColor":"#7C3AED","author":"GameMate"}'::jsonb,
  '{"enabled":false,"client":"","placements":{},"slots":{}}'::jsonb
)
on conflict (id) do nothing;
